from ..entity import Entity
from .metaenum import EnumMeta


class Entities(metaclass=EnumMeta[Entity]):
	AREA_EFFECT_CLOUD: Entity = {'id': 3, 'name': 'area_effect_cloud', 'display_name': 'Area Effect Cloud', 'category': 'UNKNOWN', 'width': 6, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ARMOR_STAND: Entity = {'id': 5, 'name': 'armor_stand', 'display_name': 'Armor Stand', 'category': 'Immobile', 'width': 0.5, 'height': 1.975, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ARROW: Entity = {'id': 6, 'name': 'arrow', 'display_name': 'Arrow', 'category': 'Projectiles', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	BAT: Entity = {'id': 10, 'name': 'bat', 'display_name': 'Bat', 'category': 'UNKNOWN', 'width': 0.5, 'height': 0.9, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	BLAZE: Entity = {'id': 14, 'name': 'blaze', 'display_name': 'Blaze', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	BOAT: Entity = {'id': 10, 'name': 'boat', 'display_name': 'Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.20.5')}
	CAVE_SPIDER: Entity = {'id': 21, 'name': 'cave_spider', 'display_name': 'Cave Spider', 'category': 'Hostile mobs', 'width': 0.7, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	CHICKEN: Entity = {'id': 25, 'name': 'chicken', 'display_name': 'Chicken', 'category': 'Passive mobs', 'width': 0.4, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	COD: Entity = {'id': 26, 'name': 'cod', 'display_name': 'Cod', 'category': 'Passive mobs', 'width': 0.5, 'height': 0.3, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	COW: Entity = {'id': 28, 'name': 'cow', 'display_name': 'Cow', 'category': 'Passive mobs', 'width': 0.9, 'height': 1.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	CREEPER: Entity = {'id': 30, 'name': 'creeper', 'display_name': 'Creeper', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	DONKEY: Entity = {'id': 34, 'name': 'donkey', 'display_name': 'Donkey', 'category': 'Passive mobs', 'width': 1.3964844, 'height': 1.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	DOLPHIN: Entity = {'id': 33, 'name': 'dolphin', 'display_name': 'Dolphin', 'category': 'Passive mobs', 'width': 0.9, 'height': 0.6, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	DRAGON_FIREBALL: Entity = {'id': 35, 'name': 'dragon_fireball', 'display_name': 'Dragon Fireball', 'category': 'Projectiles', 'width': 1, 'height': 1, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	DROWNED: Entity = {'id': 36, 'name': 'drowned', 'display_name': 'Drowned', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ELDER_GUARDIAN: Entity = {'id': 38, 'name': 'elder_guardian', 'display_name': 'Elder Guardian', 'category': 'Hostile mobs', 'width': 1.9975, 'height': 1.9975, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	END_CRYSTAL: Entity = {'id': 43, 'name': 'end_crystal', 'display_name': 'End Crystal', 'category': 'Hostile mobs', 'width': 2, 'height': 2, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ENDER_DRAGON: Entity = {'id': 41, 'name': 'ender_dragon', 'display_name': 'Ender Dragon', 'category': 'Hostile mobs', 'width': 16, 'height': 8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ENDERMAN: Entity = {'id': 39, 'name': 'enderman', 'display_name': 'Enderman', 'category': 'Hostile mobs', 'width': 0.6, 'height': 2.9, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ENDERMITE: Entity = {'id': 40, 'name': 'endermite', 'display_name': 'Endermite', 'category': 'Hostile mobs', 'width': 0.4, 'height': 0.3, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	EVOKER_FANGS: Entity = {'id': 45, 'name': 'evoker_fangs', 'display_name': 'Evoker Fangs', 'category': 'Projectiles', 'width': 0.5, 'height': 0.8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	EVOKER: Entity = {'id': 44, 'name': 'evoker', 'display_name': 'Evoker', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	EXPERIENCE_ORB: Entity = {'id': 47, 'name': 'experience_orb', 'display_name': 'Experience Orb', 'category': 'UNKNOWN', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	EYE_OF_ENDER: Entity = {'id': 48, 'name': 'eye_of_ender', 'display_name': 'Eye of Ender', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	FALLING_BLOCK: Entity = {'id': 49, 'name': 'falling_block', 'display_name': 'Falling Block', 'category': 'UNKNOWN', 'width': 0.98, 'height': 0.98, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	FIREWORKS_ROCKET: Entity = {'id': 25, 'name': 'fireworks_rocket', 'display_name': 'FireworksRocketEntity', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	GHAST: Entity = {'id': 55, 'name': 'ghast', 'display_name': 'Ghast', 'category': 'Hostile mobs', 'width': 4, 'height': 4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	GIANT: Entity = {'id': 57, 'name': 'giant', 'display_name': 'Giant', 'category': 'Hostile mobs', 'width': 3.6, 'height': 12, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	GUARDIAN: Entity = {'id': 61, 'name': 'guardian', 'display_name': 'Guardian', 'category': 'Hostile mobs', 'width': 0.85, 'height': 0.85, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	HORSE: Entity = {'id': 64, 'name': 'horse', 'display_name': 'Horse', 'category': 'Passive mobs', 'width': 1.3964844, 'height': 1.6, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	HUSK: Entity = {'id': 65, 'name': 'husk', 'display_name': 'Husk', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ILLUSIONER: Entity = {'id': 66, 'name': 'illusioner', 'display_name': 'Illusioner', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ITEM: Entity = {'id': 69, 'name': 'item', 'display_name': 'Item', 'category': 'UNKNOWN', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ITEM_FRAME: Entity = {'id': 71, 'name': 'item_frame', 'display_name': 'Item Frame', 'category': 'Immobile', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	FIREBALL: Entity = {'id': 50, 'name': 'fireball', 'display_name': 'Fireball', 'category': 'Projectiles', 'width': 1, 'height': 1, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	LEASH_KNOT: Entity = {'id': 74, 'name': 'leash_knot', 'display_name': 'Leash Knot', 'category': 'Immobile', 'width': 0.375, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	LLAMA: Entity = {'id': 76, 'name': 'llama', 'display_name': 'Llama', 'category': 'Passive mobs', 'width': 0.9, 'height': 1.87, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	LLAMA_SPIT: Entity = {'id': 77, 'name': 'llama_spit', 'display_name': 'Llama Spit', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	MAGMA_CUBE: Entity = {'id': 78, 'name': 'magma_cube', 'display_name': 'Magma Cube', 'category': 'Hostile mobs', 'width': 0.52, 'height': 0.52, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	MINECART: Entity = {'id': 82, 'name': 'minecart', 'display_name': 'Minecart', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	CHEST_MINECART: Entity = {'id': 24, 'name': 'chest_minecart', 'display_name': 'Minecart with Chest', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	COMMANDBLOCK_MINECART: Entity = {'id': 41, 'name': 'commandblock_minecart', 'display_name': 'MinecartCommandBlock', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	FURNACE_MINECART: Entity = {'id': 54, 'name': 'furnace_minecart', 'display_name': 'Minecart with Furnace', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	HOPPER_MINECART: Entity = {'id': 63, 'name': 'hopper_minecart', 'display_name': 'Minecart with Hopper', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SPAWNER_MINECART: Entity = {'id': 117, 'name': 'spawner_minecart', 'display_name': 'Minecart with Monster Spawner', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	TNT_MINECART: Entity = {'id': 128, 'name': 'tnt_minecart', 'display_name': 'Minecart with TNT', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	MULE: Entity = {'id': 84, 'name': 'mule', 'display_name': 'Mule', 'category': 'Passive mobs', 'width': 1.3964844, 'height': 1.6, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	MOOSHROOM: Entity = {'id': 83, 'name': 'mooshroom', 'display_name': 'Mooshroom', 'category': 'Passive mobs', 'width': 0.9, 'height': 1.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	OCELOT: Entity = {'id': 87, 'name': 'ocelot', 'display_name': 'Ocelot', 'category': 'Passive mobs', 'width': 0.6, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	PAINTING: Entity = {'id': 89, 'name': 'painting', 'display_name': 'Painting', 'category': 'Immobile', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	PARROT: Entity = {'id': 93, 'name': 'parrot', 'display_name': 'Parrot', 'category': 'Passive mobs', 'width': 0.5, 'height': 0.9, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	PIG: Entity = {'id': 95, 'name': 'pig', 'display_name': 'Pig', 'category': 'Passive mobs', 'width': 0.9, 'height': 0.9, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	PUFFERFISH: Entity = {'id': 102, 'name': 'pufferfish', 'display_name': 'Pufferfish', 'category': 'Passive mobs', 'width': 0.7, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ZOMBIE_PIGMAN: Entity = {'id': 57, 'name': 'zombie_pigman', 'display_name': 'Zombie Pigman', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.15.2')}
	POLAR_BEAR: Entity = {'id': 99, 'name': 'polar_bear', 'display_name': 'Polar Bear', 'category': 'Passive mobs', 'width': 1.4, 'height': 1.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	TNT: Entity = {'id': 127, 'name': 'tnt', 'display_name': 'Primed TNT', 'category': 'UNKNOWN', 'width': 0.98, 'height': 0.98, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	RABBIT: Entity = {'id': 103, 'name': 'rabbit', 'display_name': 'Rabbit', 'category': 'Passive mobs', 'width': 0.4, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SALMON: Entity = {'id': 105, 'name': 'salmon', 'display_name': 'Salmon', 'category': 'Passive mobs', 'width': 0.7, 'height': 0.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SHEEP: Entity = {'id': 106, 'name': 'sheep', 'display_name': 'Sheep', 'category': 'Passive mobs', 'width': 0.9, 'height': 1.3, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SHULKER: Entity = {'id': 107, 'name': 'shulker', 'display_name': 'Shulker', 'category': 'Hostile mobs', 'width': 1, 'height': 1, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SHULKER_BULLET: Entity = {'id': 108, 'name': 'shulker_bullet', 'display_name': 'Shulker Bullet', 'category': 'Projectiles', 'width': 0.3125, 'height': 0.3125, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SILVERFISH: Entity = {'id': 109, 'name': 'silverfish', 'display_name': 'Silverfish', 'category': 'Hostile mobs', 'width': 0.4, 'height': 0.3, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SKELETON: Entity = {'id': 110, 'name': 'skeleton', 'display_name': 'Skeleton', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.99, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SKELETON_HORSE: Entity = {'id': 111, 'name': 'skeleton_horse', 'display_name': 'Skeleton Horse', 'category': 'Passive mobs', 'width': 1.3964844, 'height': 1.6, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SLIME: Entity = {'id': 112, 'name': 'slime', 'display_name': 'Slime', 'category': 'Hostile mobs', 'width': 0.52, 'height': 0.52, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SMALL_FIREBALL: Entity = {'id': 113, 'name': 'small_fireball', 'display_name': 'Small Fireball', 'category': 'Projectiles', 'width': 0.3125, 'height': 0.3125, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SNOW_GOLEM: Entity = {'id': 116, 'name': 'snow_golem', 'display_name': 'Snow Golem', 'category': 'Passive mobs', 'width': 0.7, 'height': 1.9, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SNOWBALL: Entity = {'id': 115, 'name': 'snowball', 'display_name': 'Snowball', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SPECTRAL_ARROW: Entity = {'id': 118, 'name': 'spectral_arrow', 'display_name': 'Spectral Arrow', 'category': 'Projectiles', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SPIDER: Entity = {'id': 119, 'name': 'spider', 'display_name': 'Spider', 'category': 'Hostile mobs', 'width': 1.4, 'height': 0.9, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	SQUID: Entity = {'id': 122, 'name': 'squid', 'display_name': 'Squid', 'category': 'Passive mobs', 'width': 0.8, 'height': 0.8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	STRAY: Entity = {'id': 123, 'name': 'stray', 'display_name': 'Stray', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.99, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	TROPICAL_FISH: Entity = {'id': 131, 'name': 'tropical_fish', 'display_name': 'Tropical Fish', 'category': 'Passive mobs', 'width': 0.5, 'height': 0.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	TURTLE: Entity = {'id': 132, 'name': 'turtle', 'display_name': 'Turtle', 'category': 'Passive mobs', 'width': 1.2, 'height': 0.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	EGG: Entity = {'id': 37, 'name': 'egg', 'display_name': 'Thrown Egg', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ENDER_PEARL: Entity = {'id': 42, 'name': 'ender_pearl', 'display_name': 'Thrown Ender Pearl', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	EXPERIENCE_BOTTLE: Entity = {'id': 46, 'name': 'experience_bottle', 'display_name': "Thrown Bottle o' Enchanting", 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	POTION: Entity = {'id': 99, 'name': 'potion', 'display_name': 'Potion', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.4')}
	VEX: Entity = {'id': 133, 'name': 'vex', 'display_name': 'Vex', 'category': 'Hostile mobs', 'width': 0.4, 'height': 0.8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	VILLAGER: Entity = {'id': 134, 'name': 'villager', 'display_name': 'Villager', 'category': 'UNKNOWN', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	IRON_GOLEM: Entity = {'id': 68, 'name': 'iron_golem', 'display_name': 'Iron Golem', 'category': 'Passive mobs', 'width': 1.4, 'height': 2.7, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	VINDICATOR: Entity = {'id': 135, 'name': 'vindicator', 'display_name': 'Vindicator', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	WITCH: Entity = {'id': 139, 'name': 'witch', 'display_name': 'Witch', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	WITHER: Entity = {'id': 140, 'name': 'wither', 'display_name': 'Wither', 'category': 'Hostile mobs', 'width': 0.9, 'height': 3.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	WITHER_SKELETON: Entity = {'id': 141, 'name': 'wither_skeleton', 'display_name': 'Wither Skeleton', 'category': 'Hostile mobs', 'width': 0.7, 'height': 2.4, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	WITHER_SKULL: Entity = {'id': 142, 'name': 'wither_skull', 'display_name': 'Wither Skull', 'category': 'Projectiles', 'width': 0.3125, 'height': 0.3125, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	WOLF: Entity = {'id': 143, 'name': 'wolf', 'display_name': 'Wolf', 'category': 'Passive mobs', 'width': 0.6, 'height': 0.85, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ZOMBIE: Entity = {'id': 145, 'name': 'zombie', 'display_name': 'Zombie', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ZOMBIE_HORSE: Entity = {'id': 146, 'name': 'zombie_horse', 'display_name': 'Zombie Horse', 'category': 'Passive mobs', 'width': 1.3964844, 'height': 1.6, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ZOMBIE_VILLAGER: Entity = {'id': 147, 'name': 'zombie_villager', 'display_name': 'Zombie Villager', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	PHANTOM: Entity = {'id': 94, 'name': 'phantom', 'display_name': 'Phantom', 'category': 'Hostile mobs', 'width': 0.9, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	LIGHTNING_BOLT: Entity = {'id': 75, 'name': 'lightning_bolt', 'display_name': 'Lightning Bolt', 'category': 'UNKNOWN', 'width': 0, 'height': 0, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	PLAYER: Entity = {'id': 149, 'name': 'player', 'display_name': 'Player', 'category': 'UNKNOWN', 'width': 0.6, 'height': 1.8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	FISHING_BOBBER: Entity = {'id': 150, 'name': 'fishing_bobber', 'display_name': 'Fishing Bobber', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	TRIDENT: Entity = {'id': 130, 'name': 'trident', 'display_name': 'Trident', 'category': 'Projectiles', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ITEM_STACK: Entity = {'id': 2, 'name': 'item_stack', 'display_name': 'Item Stack ([[Slot]])', 'category': None, 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	ACTIVATED_TNT: Entity = {'id': 50, 'name': 'activated_tnt', 'display_name': 'Activated TNT', 'category': None, 'width': 0.98, 'height': 0.98, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	ENDERCRYSTAL: Entity = {'id': 51, 'name': 'endercrystal', 'display_name': 'EnderCrystal', 'category': None, 'width': 2, 'height': 2, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	TIPPED_ARROW: Entity = {'id': 60, 'name': 'tipped_arrow', 'display_name': 'Tipped arrow (projectile; also used for regular arrows)', 'category': None, 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	FIRECHARGE: Entity = {'id': 64, 'name': 'firecharge', 'display_name': 'FireCharge (blaze projectile)', 'category': None, 'width': 0.3125, 'height': 0.3125, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	THROWN_ENDERPEARL: Entity = {'id': 65, 'name': 'thrown_enderpearl', 'display_name': 'Thrown Enderpearl', 'category': None, 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	FALLING_OBJECTS: Entity = {'id': 70, 'name': 'falling_objects', 'display_name': 'Falling Objects', 'category': None, 'width': 0.98, 'height': 0.98, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	ITEM_FRAMES: Entity = {'id': 71, 'name': 'item_frames', 'display_name': 'Item frames', 'category': None, 'width': 0.75, 'height': 0.75, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	THROWN_POTION: Entity = {'id': 73, 'name': 'thrown_potion', 'display_name': 'Thrown Potion', 'category': None, 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	THROWN_EXP_BOTTLE: Entity = {'id': 75, 'name': 'thrown_exp_bottle', 'display_name': 'Thrown Exp Bottle', 'category': None, 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	FIREWORK_ROCKET: Entity = {'id': 51, 'name': 'firework_rocket', 'display_name': 'Firework Rocket', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.21.8')}
	ARMORSTAND: Entity = {'id': 78, 'name': 'armorstand', 'display_name': 'ArmorStand', 'category': None, 'width': None, 'height': None, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	EVOCATION_FANGS: Entity = {'id': 79, 'name': 'evocation_fangs', 'display_name': 'Evocation Fangs', 'category': 'Immobile', 'width': 0.5, 'height': 0.8, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	FISHING_HOOK: Entity = {'id': 90, 'name': 'fishing_hook', 'display_name': 'Fishing Hook', 'category': None, 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.13.0', '1.13.2')}
	CAT: Entity = {'id': 20, 'name': 'cat', 'display_name': 'Cat', 'category': 'Passive mobs', 'width': 0.6, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	FOX: Entity = {'id': 52, 'name': 'fox', 'display_name': 'Fox', 'category': 'Passive mobs', 'width': 0.6, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	COMMAND_BLOCK_MINECART: Entity = {'id': 27, 'name': 'command_block_minecart', 'display_name': 'Minecart with Command Block', 'category': 'Vehicles', 'width': 0.98, 'height': 0.7, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	PANDA: Entity = {'id': 92, 'name': 'panda', 'display_name': 'Panda', 'category': 'Passive mobs', 'width': 1.3, 'height': 1.25, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	TRADER_LLAMA: Entity = {'id': 129, 'name': 'trader_llama', 'display_name': 'Trader Llama', 'category': 'Passive mobs', 'width': 0.9, 'height': 1.87, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	PILLAGER: Entity = {'id': 98, 'name': 'pillager', 'display_name': 'Pillager', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	WANDERING_TRADER: Entity = {'id': 136, 'name': 'wandering_trader', 'display_name': 'Wandering Trader', 'category': 'UNKNOWN', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	RAVAGER: Entity = {'id': 104, 'name': 'ravager', 'display_name': 'Ravager', 'category': 'Hostile mobs', 'width': 1.95, 'height': 2.2, 'namespace': 'minecraft', 'versions': ('1.14.0', '1.21.8')}
	BEE: Entity = {'id': 11, 'name': 'bee', 'display_name': 'Bee', 'category': 'Passive mobs', 'width': 0.7, 'height': 0.6, 'namespace': 'minecraft', 'versions': ('1.15.2', '1.21.8')}
	HOGLIN: Entity = {'id': 62, 'name': 'hoglin', 'display_name': 'Hoglin', 'category': 'Hostile mobs', 'width': 1.3964844, 'height': 1.4, 'namespace': 'minecraft', 'versions': ('1.16.1', '1.21.8')}
	PIGLIN: Entity = {'id': 96, 'name': 'piglin', 'display_name': 'Piglin', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.16.1', '1.21.8')}
	STRIDER: Entity = {'id': 124, 'name': 'strider', 'display_name': 'Strider', 'category': 'Hostile mobs', 'width': 0.9, 'height': 1.7, 'namespace': 'minecraft', 'versions': ('1.16.1', '1.21.8')}
	ZOGLIN: Entity = {'id': 144, 'name': 'zoglin', 'display_name': 'Zoglin', 'category': 'Hostile mobs', 'width': 1.3964844, 'height': 1.4, 'namespace': 'minecraft', 'versions': ('1.16.1', '1.21.8')}
	ZOMBIFIED_PIGLIN: Entity = {'id': 148, 'name': 'zombified_piglin', 'display_name': 'Zombified Piglin', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.16.1', '1.21.8')}
	PIGLIN_BRUTE: Entity = {'id': 97, 'name': 'piglin_brute', 'display_name': 'Piglin Brute', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.95, 'namespace': 'minecraft', 'versions': ('1.16.2', '1.21.8')}
	AXOLOTL: Entity = {'id': 7, 'name': 'axolotl', 'display_name': 'Axolotl', 'category': 'Passive mobs', 'width': 0.75, 'height': 0.42, 'namespace': 'minecraft', 'versions': ('1.17.0', '1.21.8')}
	GLOW_ITEM_FRAME: Entity = {'id': 58, 'name': 'glow_item_frame', 'display_name': 'Glow Item Frame', 'category': 'Immobile', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.17.0', '1.21.8')}
	GLOW_SQUID: Entity = {'id': 59, 'name': 'glow_squid', 'display_name': 'Glow Squid', 'category': 'UNKNOWN', 'width': 0.8, 'height': 0.8, 'namespace': 'minecraft', 'versions': ('1.17.0', '1.21.8')}
	GOAT: Entity = {'id': 60, 'name': 'goat', 'display_name': 'Goat', 'category': 'Passive mobs', 'width': 0.9, 'height': 1.3, 'namespace': 'minecraft', 'versions': ('1.17.0', '1.21.8')}
	MARKER: Entity = {'id': 81, 'name': 'marker', 'display_name': 'Marker', 'category': 'UNKNOWN', 'width': 0, 'height': 0, 'namespace': 'minecraft', 'versions': ('1.17.0', '1.21.8')}
	ALLAY: Entity = {'id': 2, 'name': 'allay', 'display_name': 'Allay', 'category': 'Passive mobs', 'width': 0.35, 'height': 0.6, 'namespace': 'minecraft', 'versions': ('1.19.0', '1.21.8')}
	CHEST_BOAT: Entity = {'id': 17, 'name': 'chest_boat', 'display_name': 'Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.19.0', '1.20.5')}
	FROG: Entity = {'id': 53, 'name': 'frog', 'display_name': 'Frog', 'category': 'Passive mobs', 'width': 0.5, 'height': 0.5, 'namespace': 'minecraft', 'versions': ('1.19.0', '1.21.8')}
	TADPOLE: Entity = {'id': 125, 'name': 'tadpole', 'display_name': 'Tadpole', 'category': 'Passive mobs', 'width': 0.4, 'height': 0.3, 'namespace': 'minecraft', 'versions': ('1.19.0', '1.21.8')}
	WARDEN: Entity = {'id': 137, 'name': 'warden', 'display_name': 'Warden', 'category': 'Hostile mobs', 'width': 0.9, 'height': 2.9, 'namespace': 'minecraft', 'versions': ('1.19.0', '1.21.8')}
	CAMEL: Entity = {'id': 19, 'name': 'camel', 'display_name': 'Camel', 'category': 'Passive mobs', 'width': 1.7, 'height': 2.375, 'namespace': 'minecraft', 'versions': ('1.19.3', '1.21.8')}
	BLOCK_DISPLAY: Entity = {'id': 15, 'name': 'block_display', 'display_name': 'Block Display', 'category': 'UNKNOWN', 'width': 0, 'height': 0, 'namespace': 'minecraft', 'versions': ('1.19.4', '1.21.8')}
	INTERACTION: Entity = {'id': 67, 'name': 'interaction', 'display_name': 'Interaction', 'category': 'UNKNOWN', 'width': 0, 'height': 0, 'namespace': 'minecraft', 'versions': ('1.19.4', '1.21.8')}
	ITEM_DISPLAY: Entity = {'id': 70, 'name': 'item_display', 'display_name': 'Item Display', 'category': 'UNKNOWN', 'width': 0, 'height': 0, 'namespace': 'minecraft', 'versions': ('1.19.4', '1.21.8')}
	SNIFFER: Entity = {'id': 114, 'name': 'sniffer', 'display_name': 'Sniffer', 'category': 'Passive mobs', 'width': 1.9, 'height': 1.75, 'namespace': 'minecraft', 'versions': ('1.19.4', '1.21.8')}
	TEXT_DISPLAY: Entity = {'id': 126, 'name': 'text_display', 'display_name': 'Text Display', 'category': 'UNKNOWN', 'width': 0, 'height': 0, 'namespace': 'minecraft', 'versions': ('1.19.4', '1.21.8')}
	BREEZE: Entity = {'id': 17, 'name': 'breeze', 'display_name': 'Breeze', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.77, 'namespace': 'minecraft', 'versions': ('1.20.3', '1.21.8')}
	WIND_CHARGE: Entity = {'id': 138, 'name': 'wind_charge', 'display_name': 'Wind Charge', 'category': 'Projectiles', 'width': 0.3125, 'height': 0.3125, 'namespace': 'minecraft', 'versions': ('1.20.3', '1.21.8')}
	ARMADILLO: Entity = {'id': 4, 'name': 'armadillo', 'display_name': 'Armadillo', 'category': 'Passive mobs', 'width': 0.7, 'height': 0.65, 'namespace': 'minecraft', 'versions': ('1.20.5', '1.21.8')}
	BOGGED: Entity = {'id': 16, 'name': 'bogged', 'display_name': 'Bogged', 'category': 'Hostile mobs', 'width': 0.6, 'height': 1.99, 'namespace': 'minecraft', 'versions': ('1.20.5', '1.21.8')}
	BREEZE_WIND_CHARGE: Entity = {'id': 18, 'name': 'breeze_wind_charge', 'display_name': 'Wind Charge', 'category': 'Projectiles', 'width': 0.3125, 'height': 0.3125, 'namespace': 'minecraft', 'versions': ('1.20.5', '1.21.8')}
	OMINOUS_ITEM_SPAWNER: Entity = {'id': 88, 'name': 'ominous_item_spawner', 'display_name': 'Ominous Item Spawner', 'category': 'UNKNOWN', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.20.5', '1.21.8')}
	ACACIA_BOAT: Entity = {'id': 0, 'name': 'acacia_boat', 'display_name': 'Acacia Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	ACACIA_CHEST_BOAT: Entity = {'id': 1, 'name': 'acacia_chest_boat', 'display_name': 'Acacia Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	BAMBOO_CHEST_RAFT: Entity = {'id': 8, 'name': 'bamboo_chest_raft', 'display_name': 'Bamboo Raft with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	BAMBOO_RAFT: Entity = {'id': 9, 'name': 'bamboo_raft', 'display_name': 'Bamboo Raft', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	BIRCH_BOAT: Entity = {'id': 12, 'name': 'birch_boat', 'display_name': 'Birch Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	BIRCH_CHEST_BOAT: Entity = {'id': 13, 'name': 'birch_chest_boat', 'display_name': 'Birch Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	CHERRY_BOAT: Entity = {'id': 22, 'name': 'cherry_boat', 'display_name': 'Cherry Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	CHERRY_CHEST_BOAT: Entity = {'id': 23, 'name': 'cherry_chest_boat', 'display_name': 'Cherry Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	CREAKING: Entity = {'id': 29, 'name': 'creaking', 'display_name': 'Creaking', 'category': 'Hostile mobs', 'width': 0.9, 'height': 2.7, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	CREAKING_TRANSIENT: Entity = {'id': 30, 'name': 'creaking_transient', 'display_name': 'Creaking', 'category': 'Hostile mobs', 'width': 0.9, 'height': 2.7, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.3')}
	DARK_OAK_BOAT: Entity = {'id': 31, 'name': 'dark_oak_boat', 'display_name': 'Dark Oak Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	DARK_OAK_CHEST_BOAT: Entity = {'id': 32, 'name': 'dark_oak_chest_boat', 'display_name': 'Dark Oak Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	JUNGLE_BOAT: Entity = {'id': 72, 'name': 'jungle_boat', 'display_name': 'Jungle Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	JUNGLE_CHEST_BOAT: Entity = {'id': 73, 'name': 'jungle_chest_boat', 'display_name': 'Jungle Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	MANGROVE_BOAT: Entity = {'id': 79, 'name': 'mangrove_boat', 'display_name': 'Mangrove Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	MANGROVE_CHEST_BOAT: Entity = {'id': 80, 'name': 'mangrove_chest_boat', 'display_name': 'Mangrove Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	OAK_BOAT: Entity = {'id': 85, 'name': 'oak_boat', 'display_name': 'Oak Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	OAK_CHEST_BOAT: Entity = {'id': 86, 'name': 'oak_chest_boat', 'display_name': 'Oak Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	PALE_OAK_BOAT: Entity = {'id': 90, 'name': 'pale_oak_boat', 'display_name': 'Pale Oak Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	PALE_OAK_CHEST_BOAT: Entity = {'id': 91, 'name': 'pale_oak_chest_boat', 'display_name': 'Pale Oak Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	SPRUCE_BOAT: Entity = {'id': 120, 'name': 'spruce_boat', 'display_name': 'Spruce Boat', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	SPRUCE_CHEST_BOAT: Entity = {'id': 121, 'name': 'spruce_chest_boat', 'display_name': 'Spruce Boat with Chest', 'category': 'Vehicles', 'width': 1.375, 'height': 0.5625, 'namespace': 'minecraft', 'versions': ('1.21.3', '1.21.8')}
	SPLASH_POTION: Entity = {'id': 100, 'name': 'splash_potion', 'display_name': 'Splash Potion', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.21.5', '1.21.8')}
	LINGERING_POTION: Entity = {'id': 101, 'name': 'lingering_potion', 'display_name': 'Lingering Potion', 'category': 'Projectiles', 'width': 0.25, 'height': 0.25, 'namespace': 'minecraft', 'versions': ('1.21.5', '1.21.8')}
	HAPPY_GHAST: Entity = {'id': 56, 'name': 'happy_ghast', 'display_name': 'Happy Ghast', 'category': 'Passive mobs', 'width': 4, 'height': 4, 'namespace': 'minecraft', 'versions': ('1.21.6', '1.21.8')}